configs:
  - src: nvim/
    dst: ~/.config/nvim/
    platform: [linux, darwin]

  - src: zsh/zshrc
    dst: ~/.zshrc
    platform: [darwin]

  - src: tmux/tmux.conf
    dst: ~/.tmux.conf
    platform: [darwin, linux]

  - src: python/.pythonrc.py
    dst: ~/.pythonrc.py
    platform: [darwin, linux]

  - src: alacritty/
    dst: ~/.config/alacritty/
    platform: [darwin, linux]

  - src: etc/bashrc
    dst: ~/.bashrc_personal
    platform: [linux]
    append:
      line: 'source ~/.bashrc_personal'
      file: ~/.bashrc

  - src: etc/inputrc
    dst: ~/.inputrc
    platform: [linux]

  #Â MacOS window management
  - src: etc/aerospace.toml
    dst: ~/.aerospace.toml
    platform: [darwin]

  # ECA - Editor Code Assistant
  - src: etc/eca_config.json
    dst: ~/.config/eca/config.json
    platform: [darwin, linux]

  - src: etc/starship.toml
    dst: ~/.config/starship.toml
    platform: [darwin, linux]
